/**
 * Registro único de ícones do aplicativo.
 *
 * Regra: TODO ícone da aplicação vem do set `lucide-react`.
 * Não importe outros pacotes de ícones (react-icons, heroicons, etc.)
 * nem use SVGs inline/emoji para representar ações ou entidades.
 *
 * Use os aliases semânticos abaixo para evitar duplicidade
 * (ex.: nunca usar `Edit` e `Pencil` para a mesma ação).
 */
import {
  LayoutDashboard,
  ShoppingCart,
  Wallet,
  Package,
  Boxes,
  Warehouse,
  CalendarClock,
  Users,
  UserPlus,
  UserCog,
  Truck,
  DollarSign,
  Banknote,
  CreditCard,
  QrCode,
  Receipt,
  FileText,
  BarChart3,
  Settings,
  Shield,
  Gift,
  Tag,
  Percent,
  Plus,
  Minus,
  Pencil,
  Trash2,
  Save,
  X,
  Check,
  CheckCircle2,
  AlertTriangle,
  Info,
  Search,
  Filter,
  Download,
  Upload,
  FileSpreadsheet,
  Printer,
  Barcode,
  Calendar,
  Clock,
  Loader2,
  MoreHorizontal,
  TrendingUp,
  TrendingDown,
  ArrowUpCircle,
  ArrowDownCircle,
  RotateCcw,
  History,
  LogOut,
  Eye,
  EyeOff,
  Copy,
  Building2,
  UtensilsCrossed,
  Plug,
} from "lucide-react";

export const Icons = {
  // Navegação / módulos
  dashboard: LayoutDashboard,
  pdv: ShoppingCart,
  cash: Wallet,
  products: Package,
  stock: Boxes,
  warehouse: Warehouse,
  expiry: CalendarClock,
  customers: Users,
  team: UserCog,
  suppliers: Truck,
  financial: DollarSign,
  fiscal: FileText,
  reports: BarChart3,
  settings: Settings,
  admin: Shield,
  loyalty: Gift,
  tables: UtensilsCrossed,
  company: Building2,
  integrations: Plug,

  // Pagamentos
  cashPayment: Banknote,
  card: CreditCard,
  pix: QrCode,
  receipt: Receipt,

  // Ações
  add: Plus,
  remove: Minus,
  edit: Pencil,
  delete: Trash2,
  save: Save,
  close: X,
  confirm: Check,
  success: CheckCircle2,
  warning: AlertTriangle,
  info: Info,
  search: Search,
  filter: Filter,
  export: Download,
  exportExcel: FileSpreadsheet,
  import: Upload,
  print: Printer,
  barcode: Barcode,
  date: Calendar,
  time: Clock,
  loading: Loader2,
  more: MoreHorizontal,
  refresh: RotateCcw,
  history: History,
  logout: LogOut,
  show: Eye,
  hide: EyeOff,
  copy: Copy,
  invite: UserPlus,
  discount: Percent,
  tag: Tag,

  // Indicadores
  up: TrendingUp,
  down: TrendingDown,
  in: ArrowUpCircle,
  out: ArrowDownCircle,
} as const;

export type IconName = keyof typeof Icons;
