// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Referência preenchida logo após a criação do client (ver abaixo). O fetch
// customizado só é chamado em requisições futuras, então esse "forward
// reference" é seguro: por quando ele roda, `client` já foi atribuído.
let client: SupabaseClient<Database>;

/**
 * Evita o "toda hora pede login de novo": quando uma chamada à API volta
 * com 401 por token expirado (PGRST301 / "jwt expired"), renova a sessão
 * uma vez e repete a mesma requisição antes de propagar o erro. Sem isso,
 * qualquer corrida entre a expiração do token e a renovação automática do
 * SDK vira um erro visível na tela (Caixa, Configurações, etc.) mesmo com
 * a sessão ainda válida.
 */
const fetchWithAuthRetry: typeof fetch = async (input, init) => {
  const response = await fetch(input, init);

  if (response.status !== 401) return response;

  let isExpiredToken = false;
  try {
    const body = await response.clone().json();
    isExpiredToken = body?.code === 'PGRST301' || /jwt expired/i.test(body?.message ?? '');
  } catch {
    // resposta sem corpo JSON: não mexe, devolve a resposta original
  }
  if (!isExpiredToken) return response;

  try {
    const { data, error } = await client.auth.refreshSession();
    if (error || !data.session) return response;

    const headers = new Headers(init?.headers);
    headers.set('Authorization', `Bearer ${data.session.access_token}`);
    return await fetch(input, { ...init, headers });
  } catch {
    return response;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithAuthRetry,
  },
});
client = supabase;
